"use client";
import { useState, useEffect, useCallback } from 'react';
import PageHero from "./PageHero";
import Link from 'next/link';
import { fxbookSlides, testimonials } from "../data/content";
import CountUp from "../components/CountUp";
import "./shared-page.css";
import "./ResultsPage.css";
import Icon from "../components/Icon";

const MFX_SLIDES = [
  {
    image: "/images/atr-grid-3d-chart.png",
    alt: "Live Tracking",
    badge: "LIVE SYNC",
    title: "100% Live Tracking",
    desc: "Data synced directly from the broker backend in real-time. Every trade, every tick — completely tamper-proof and impossible to alter.",
    stat: { value: "Real-Time", label: "Data Sync" }
  },
  {
    image: "/images/strategy-diagram.png",
    alt: "Advanced Analytics",
    badge: "DEEP METRICS",
    title: "Advanced Analytics",
    desc: "Deep-dive into every metric including drawdown, Performance Factor, and monthly growth rates. No vanity metrics — just the raw truth.",
    stat: { value: "15+", label: "Metrics Tracked" }
  },
  {
    image: "/images/atr-grid-3d-chart-1.png",
    alt: "Absolute Transparency",
    badge: "VERIFIED",
    title: "Absolute Transparency",
    desc: "No hidden losses. Every single trade executed by AURUM is permanently logged and visible to anyone — at any time.",
    stat: { value: "100%", label: "Open Record" }
  }
];

function MfxCarousel() {
  const [index, setIndex] = useState(0);
  const [paused, setPaused] = useState(false);
  const total = MFX_SLIDES.length;

  const goTo = useCallback((i) => {
    setIndex(((i % total) + total) % total);
  }, [total]);

  useEffect(() => {
    if (paused) return;
    const id = setInterval(() => goTo(index + 1), 4500);
    return () => clearInterval(id);
  }, [index, paused, goTo]);

  const slide = MFX_SLIDES[index];

  return (
    <div
      className="mfx-carousel-v2"
      onMouseEnter={() => setPaused(true)}
      onMouseLeave={() => setPaused(false)}
    >
      {/* Frame */}
      <div className="mfx-carousel-v2__frame">
        {MFX_SLIDES.map((s, i) => (
          <img
            key={s.image}
            src={s.image}
            alt={s.alt}
            className={`mfx-carousel-v2__img ${i === index ? 'is-active' : ''}`}
          />
        ))}
        {/* Badge */}
        <span className="mfx-carousel-v2__badge">{slide.badge}</span>
        {/* Nav arrows */}
        <button type="button" className="mfx-carousel-v2__arrow mfx-carousel-v2__arrow--prev" onClick={() => goTo(index - 1)} aria-label="Previous">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M15 6l-6 6 6 6" strokeLinecap="round" strokeLinejoin="round"/></svg>
        </button>
        <button type="button" className="mfx-carousel-v2__arrow mfx-carousel-v2__arrow--next" onClick={() => goTo(index + 1)} aria-label="Next">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M9 6l6 6-6 6" strokeLinecap="round" strokeLinejoin="round"/></svg>
        </button>
      </div>

      {/* Body text */}
      <div className="mfx-carousel-v2__body" key={slide.title}>
        <div className="mfx-carousel-v2__stat">
          <strong>{slide.stat.value}</strong>
          <span>{slide.stat.label}</span>
        </div>
        <div className="mfx-carousel-v2__copy">
          <h3 className="mfx-carousel-v2__title">{slide.title}</h3>
          <p className="mfx-carousel-v2__desc">{slide.desc}</p>
        </div>
      </div>

      {/* Dots */}
      <div className="mfx-carousel-v2__dots">
        {MFX_SLIDES.map((_, i) => (
          <button
            key={i}
            className={`mfx-carousel-v2__dot ${i === index ? 'is-active' : ''}`}
            onClick={() => goTo(i)}
            aria-label={`Go to slide ${i + 1}`}
          />
        ))}
      </div>
    </div>
  );
}

const TRUST_ITEMS = [
  { title: "Real Accounts", text: "Live trading results from real traders." },
  { title: "Verified by MyFXBook", text: "Industry standard verification." },
  { title: "100% Transparent", text: "No filters. No fake promises." },
  { title: "150+ Traders", text: "And growing every day." }
];

const RESULT_STATS = [
  { value: "$272k+", label: "Returns generated by AURUM users so far" },
  { value: "150+", label: "Traders making money with AURUM" },
  { value: "1.5 yrs", label: "Live track record, verified on MyFXBook" },
  { value: "24/7", label: "Automated execution on live accounts" }
];

const fxbookTotals = {
  profit: fxbookSlides.reduce((sum, s) => sum + Number(s.profit.replace(/[^0-9.]/g, "")), 0),
  trades: fxbookSlides.reduce((sum, s) => sum + s.trades, 0),
  avgGrowth: fxbookSlides.reduce((sum, s) => sum + parseFloat(s.growth), 0) / fxbookSlides.length,
  avgDrawdown: fxbookSlides.reduce((sum, s) => sum + parseFloat(s.drawdown), 0) / fxbookSlides.length
};

const FXBOOK_SUMMARY = [
  { value: `$${(fxbookTotals.profit / 1000).toFixed(1)}k`, label: `Returns in the last ${fxbookSlides.length} months` },
  { value: `+${fxbookTotals.avgGrowth.toFixed(1)}%`, label: "Average monthly growth", positive: true },
  { value: `${fxbookTotals.avgDrawdown.toFixed(1)}%`, label: "Average max drawdown" },
  { value: `${fxbookTotals.trades}`, label: "Trades executed" }
];

export default function ResultsPage() {
  return (
    <main>
      <PageHero
        eyebrow="Performance"
        title="Real Accounts. Real Results."
        lead="150+ active traders. 1.5 years of live performance. These aren't demo screenshots or backtested curves — this is what AURUM has done, and continues to do, on live accounts every day."
        badge="150+ active traders · $272k+ user returns · 1.5 years live track record"
        note="Results vary by account size, broker, and risk settings. Past performance does not guarantee future results. Always trade with capital you can afford to lose."
      />

      <section className="section section--tight">
        <div className="container">
          <div className="stats-row reveal">
            {RESULT_STATS.map((s) => (
              <div className="stat-block" key={s.label}>
                <div className="stat-block__n">
                  <CountUp value={s.value} />
                </div>
                <p className="stat-block__l">{s.label}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="section mfx-banner">
        <div className="container">
          <div className="mfx-banner__content reveal">
            <p className="eyebrow">Don&apos;t Trust Our Words. Trust the Live Broker Data.</p>
            <h2>What Our Myfxbook Verification Means for Your Peace of Mind</h2>
            <p className="mfx-banner__lead">
              Myfxbook is an uncheatable third-party auditor that live-tracks our product&apos;s exact performance. It completely eliminates guesswork by pulling trading data directly from the exchange backend. You see the real wins, the real losses, and the real math—giving you the ultimate proof of consistency.
            </p>
            <MfxCarousel />
          </div>
        </div>
      </section>

      <section className="section section--grey">
        <div className="container">
          <div className="section-head section-head--center reveal">
            <p className="eyebrow">Verified Performance</p>
            <h2>MyFXBook verified. No cherry-picking.</h2>
            <p>
              We use MyFXBook — the industry standard for independently verified trading results
              — to give you transparent, tamper-proof performance data from live AURUM accounts.
            </p>
          </div>

          <div className="fxbook-summary reveal">
            {FXBOOK_SUMMARY.map((s) => (
              <div className="fxbook-summary__item" key={s.label}>
                <div className={`fxbook-summary__v ${s.positive ? "is-positive" : ""}`}>
                  <CountUp value={s.value} />
                </div>
                <div className="fxbook-summary__l">{s.label}</div>
              </div>
            ))}
          </div>

          <div className="fxbook-grid reveal">
            {fxbookSlides.map((s) => (
              <div className="fxbook-card" key={s.month}>
                <div className="fxbook-card__month">
                  {s.month}
                  <span className="fxbook-card__verified">
                    <span className="fxbook-card__dot" aria-hidden="true" />
                    Verified
                  </span>
                </div>
                <div className="fxbook-card__growth">
                  <CountUp value={s.growth} />
                </div>
                <div className="fxbook-card__growth-label">Monthly growth</div>
                <div className="fxbook-card__stats">
                  <div className="fxbook-card__stat">
                    <div className="fxbook-card__v">
                      <CountUp value={s.profit} />
                    </div>
                    <div className="fxbook-card__l">Returns</div>
                  </div>
                  <div className="fxbook-card__stat">
                    <div className="fxbook-card__v">
                      <CountUp value={s.drawdown} />
                    </div>
                    <div className="fxbook-card__l">Max Drawdown</div>
                  </div>
                  <div className="fxbook-card__stat">
                    <div className="fxbook-card__v">
                      <CountUp value={s.trades} />
                    </div>
                    <div className="fxbook-card__l">Trades</div>
                  </div>
                </div>
              </div>
            ))}
          </div>
          <div className="fxbook-actions reveal">
            <a
              href="https://www.myfxbook.com"
              target="_blank"
              rel="noreferrer"
              className="btn btn--gold"
            >
              View the Live MyFXBook Report
            </a>
          </div>

          <p className="perf-note">
            Indicative figures from live AURUM accounts. Individual results vary based on account
            size, broker, and risk settings.
          </p>
        </div>
      </section>
      
      <section className="section results-community">
        <div className="container">
          <div className="section-head section-head--center reveal">
            <p className="eyebrow">Real Traders. Real Results.</p>
            <h2>150+ traders. $272k+ in combined returns.</h2>
            <p>These are the people behind the numbers — real accounts, real returns, in their own words.</p>
          </div>

          <div className="results-testi-grid">
            {testimonials.map((t, idx) => (
              <div className={`results-testi-card reveal ${t.isCta ? "results-testi-card--cta" : ""}`} key={t.name || idx}>
                {t.isCta ? (
                  <div className="results-testi-card__cta-content">
                    <h3 className="results-testi-card__cta-title">{t.title}</h3>
                    <Link href={t.buttonLink} className="btn btn--gold">{t.buttonText}</Link>
                  </div>
                ) : (
                  <>
                    <div className="results-testi-card__meta">
                      <span className="results-testi-card__profit">{t.profit}</span>
                      <span className="results-testi-card__joined">{t.joined}</span>
                    </div>
                    <p className="results-testi-card__text">&ldquo;{t.text}&rdquo;</p>
                    <div className="results-testi-card__author">
                      <span className="results-testi-card__av">{t.name.split(" ").map((w) => w[0]).join("")}</span>
                      <div>
                        <div className="results-testi-card__name">{t.name}</div>
                        <div className="results-testi-card__role">Rating: {"\u2605".repeat(t.rating)}{"\u2606".repeat(5 - t.rating)}</div>
                      </div>
                    </div>
                  </>
                )}
              </div>
            ))}
          </div>

          <div className="results-trust reveal">
            {TRUST_ITEMS.map((item) => (
              <div className="results-trust__item" key={item.title}>
                <strong>{item.title}</strong>
                <p>{item.text}</p>
              </div>
            ))}
          </div>

          <p className="risk-banner reveal">
            Important: all testimonials reflect individual experiences and results. Trading
            results vary significantly based on account size, broker conditions, risk settings,
            and market timing. Trading carries substantial risk of loss.
          </p>
        </div>
      </section>

      <section className="section section--tight cta-block">
        <div className="container cta-block__inner reveal">
          <p className="eyebrow">Your Turn</p>
          <h2>You&apos;ve seen the results. Now get them.</h2>
          <p>
            150+ traders started where you are right now — reading this page, wondering if it&apos;s
            real. The only way to know is to start.
          </p>
          <div className="cta-block__actions">
            <Link href="/pricing" className="btn btn--gold">Get AURUM Now</Link>
            <Link href="/contact" className="btn btn--ghost">Talk to the Team First</Link>
          </div>
        </div>
      </section>
    </main>
  );
}
