"use client";
import { useState } from "react";
import { pricingTiers } from "../data/content";
import Icon from "./Icon";
import "./Pricing.css";

function TierIcon({ name }) {
  if (name === "Silver") {
    return (
      <svg width="28" height="28" viewBox="0 0 24 24" fill="none" aria-hidden="true">
        <circle cx="12" cy="8" r="4" stroke="currentColor" strokeWidth="1.8" />
        <path d="M6 20c1.5-3 4-4.5 6-4.5S16.5 17 18 20" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" />
        <path d="M9 8h6M12 5v6" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
      </svg>
    );
  }
  if (name === "Gold") {
    return (
      <svg width="28" height="28" viewBox="0 0 24 24" fill="none" aria-hidden="true">
        <path d="M12 3l2.4 4.9L20 9l-4 3.9.9 5.6L12 16.2 7.1 18.5 8 12.9 4 9l5.6-1.1L12 3z" stroke="currentColor" strokeWidth="1.6" strokeLinejoin="round" />
      </svg>
    );
  }
  return (
    <svg width="28" height="28" viewBox="0 0 24 24" fill="none" aria-hidden="true">
      <path d="M12 3l7 4v6c0 4.2-2.8 7.5-7 9-4.2-1.5-7-4.8-7-9V7l7-4z" stroke="currentColor" strokeWidth="1.7" strokeLinejoin="round" />
      <path d="M12 8v8M9 11.5h6" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" />
    </svg>
  );
}

function FeatureMark({ included }) {
  if (included) {
    return (
      <span className="price-card__mark price-card__mark--yes" aria-hidden="true">
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none">
          <path d="M5 13l4 4L19 7" stroke="currentColor" strokeWidth="2.6" strokeLinecap="round" strokeLinejoin="round" />
        </svg>
      </span>
    );
  }
  return (
    <span className="price-card__mark price-card__mark--no" aria-hidden="true">
      <svg width="12" height="12" viewBox="0 0 24 24" fill="none">
        <path d="M6 6l12 12M18 6L6 18" stroke="currentColor" strokeWidth="2.6" strokeLinecap="round" />
      </svg>
    </span>
  );
}

function ChevronIcon() {
  return (
    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" aria-hidden="true">
      <path d="M6 9l6 6 6-6" stroke="currentColor" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  );
}

function FeaturesList({ tier }) {
  return (
    <ul className="price-card__features">
      {tier.featureRows.map((row) => (
        <li
          key={`${row.label}-${row.value || "x"}`}
          className={row.included ? "" : "is-excluded"}
        >
          <FeatureMark included={row.included} />
          <span>
            {row.value ? (
              <>
                <strong>{row.label}:</strong>{" "}
                <span className={row.emphasize ? "is-emphasis" : ""}>{row.value}</span>
              </>
            ) : (
              row.label
            )}
          </span>
        </li>
      ))}
    </ul>
  );
}

export default function Pricing({ compact = false }) {
  const [expandedPlans, setExpandedPlans] = useState(() =>
    Object.fromEntries(pricingTiers.map((tier) => [tier.id, false]))
  );
  const [loadingPlan, setLoadingPlan] = useState(null);

  const togglePlan = (id) => {
    setExpandedPlans((prev) => ({ ...prev, [id]: !prev[id] }));
  };

  const handleCheckout = async (planId) => {
    setLoadingPlan(planId);
    try {
      const res = await fetch("/api/create-checkout-session", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ planId }),
      });
      const data = await res.json();
      if (data.url) {
        window.location.href = data.url;
      } else {
        alert(data.error || "Failed to create checkout session.");
        setLoadingPlan(null);
      }
    } catch (err) {
      console.error(err);
      alert("An error occurred. Please try again.");
      setLoadingPlan(null);
    }
  };

  return (
    <section id="pricing" className="section section--tight section--white pricing">
      <div className="container">
        <div className="section-head section-head--center pricing__head reveal">
          <p className="eyebrow">Pricing</p>
          <h2>Choose Your Trading Edge</h2>
          <p>Join 150+ successful traders using our proven system</p>

          <div className="pricing__trust">
            <Icon name="check" size={18} strokeWidth={2.2} />
            <span>
              Established system with a proven track record — $230K+ in results generated by our active users.
            </span>
          </div>

          <div className="pricing__meta">
            <div className="pricing__stars" aria-label="5 star rating">
              {Array.from({ length: 5 }).map((_, i) => (
                <svg key={i} width="16" height="16" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
                  <path d="M12 3l2.7 5.5 6.1.9-4.4 4.3 1 6.1L12 17.8 6.6 20l1-6.1L3.2 9.4l6.1-.9L12 3z" />
                </svg>
              ))}
            </div>
            <div className="pricing__secure">
              <Icon name="shield" size={15} strokeWidth={2} />
              <span>Secure Payment</span>
            </div>
          </div>
        </div>

        <div className={`pricing-grid ${compact ? "pricing-grid--compact" : ""}`}>
          {pricingTiers.map((tier, i) => {
            const isOpen = compact && expandedPlans[tier.id];

            return (
              <article
                id={`${tier.name.toLowerCase()}-pricing-card`}
                className={`price-card ${tier.featured ? "price-card--featured" : ""} ${
                  compact ? "price-card--compact" : ""
                } ${isOpen ? "is-open" : ""}`}
                style={{ "--reveal-delay": `${i * 100}ms` }}
                key={tier.id}
              >
                {tier.popular && <span className="price-card__badge">Most Popular</span>}
                {tier.bestSeller && <span className="price-card__ribbon">Best Seller</span>}

                <div className="price-card__icon">
                  <TierIcon name={tier.name} />
                </div>

                <h3>{tier.name}</h3>
                <p className="price-card__audience">{tier.audience}</p>
                <span className="price-card__highlight">{tier.highlight}</span>

                <div className="price-card__price">
                  <span className="price-card__amount">{tier.price}</span>
                  <span className="price-card__period">/lifetime</span>
                </div>

                {compact ? (
                  <>
                    <div className="price-card__actions">
                      <button
                        type="button"
                        onClick={() => handleCheckout(tier.id)}
                        disabled={loadingPlan === tier.id}
                        className={`btn price-card__cta btn--${tier.variant}`}
                      >
                        {loadingPlan === tier.id ? "Processing…" : `Choose ${tier.name}`}
                      </button>
                      <button
                        type="button"
                        className={`price-card__dropdown-toggle ${isOpen ? "is-open" : ""}`}
                        onClick={() => togglePlan(tier.id)}
                        aria-expanded={isOpen}
                        aria-label={isOpen ? "Hide details" : "Show details"}
                        aria-controls={`price-card-panel-${tier.id}`}
                      >
                        <ChevronIcon />
                      </button>
                    </div>

                    <div className="price-card__panel" id={`price-card-panel-${tier.id}`}>
                      <div className="price-card__panel-inner">
                        <p className="price-card__fee">One-time payment, no recurring fees</p>
                        <p className="price-card__features-heading">{tier.featuresHeading}</p>
                        <FeaturesList tier={tier} />
                        <p className="price-card__support">{tier.supportNote}</p>
                      </div>
                    </div>
                  </>
                ) : (
                  <>
                    <p className="price-card__fee">One-time payment, no recurring fees</p>
                    <p className="price-card__features-heading">{tier.featuresHeading}</p>
                    <FeaturesList tier={tier} />
                    <button
                      type="button"
                      onClick={() => handleCheckout(tier.id)}
                      disabled={loadingPlan === tier.id}
                      className={`btn price-card__cta btn--${tier.variant}`}
                    >
                      {loadingPlan === tier.id ? "Processing…" : `Choose ${tier.name}`}
                    </button>
                    <p className="price-card__support">{tier.supportNote}</p>
                  </>
                )}
              </article>
            );
          })}
        </div>
      </div>
    </section>
  );
}
